version: "3"
networks:
  celec-blog-network:
services:
 imgproxy:
    image: darthsim/imgproxy
    environment:  
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: "/src"
      IMGPROXY_KEY: ""
      IMGPROXY_SALT: ""
      IMGPROXY_CACHE_CONTROL_PASSTHROUGH: 1
      IMGPROXY_MAX_SRC_RESOLUTION: 999999
      IMGPROXY_USE_ETAG: 1
    volumes:
      - ./src:/src
    networks:
     - celec-blog-network
 varnish:
    image: varnish:stable
    container_name: varnish
    volumes:
      - "./varnish/default.vcl:/etc/varnish/default.vcl"
    ports:
      - "7000:80"
    tmpfs:
      - /var/lib/varnish:exec
    environment:
      - VARNISH_SIZE=2G  
    command: "-p default_keep=300"
    networks:
      - celec-blog-network
    depends_on:
      - "php-apache-environment"
 php-apache-environment:
  networks:
   - celec-blog-network
  container_name: php-blog-apache
  build:
   context: ./php
   dockerfile: Dockerfile
  volumes: 
   - ./src/:/var/www/html/
   - ./php/config.ini:/usr/local/etc/php/conf.d/uploads-config.ini
   - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
 mariadb:
  container_name: mariadb-celec-blog
  networks:
   - celec-blog-network
  image: mariadb
  environment:
   MARIADB_ROOT_PASSWORD: root
  ports:
   - "7306:3306"

